name: validate
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  push:
    branches: ['main']
  pull_request:
    branches: ['*']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    timeout-minutes: 60
    env:
      TEMPLATE_PATH: ''
      UNITY_EDITOR_PATH: '' # set from unity-setup step
      UNITY_PROJECT_PATH: '${{ github.workspace }}/Test Project'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        unity-version: [2022.3.x, 6000.0.x, 6000.1.x]
        include: # for each os specify the build targets
          - os: ubuntu-latest
            build-target: StandaloneLinux64
          - os: windows-latest
            build-target: StandaloneWindows64
          - os: macos-latest
            build-target: StandaloneOSX
    steps:
      - uses: actions/checkout@v4
      - run: 'npm install -g openupm-cli'
        # Installs the Unity Editor based on your project version text file
        # sets -> env.UNITY_EDITOR_PATH
        # sets -> env.UNITY_PROJECT_PATH
      - uses: buildalon/unity-setup@v1
        with:
          version-file: 'None'
          build-targets: ${{ matrix.build-target }}
          unity-version: ${{ matrix.unity-version }}
      - name: Find Unity Template Path
        id: template
        run: |
          UNITY_EDITOR_PATH="${{ env.UNITY_EDITOR_PATH }}//\\//}"
          root_path="${UNITY_EDITOR_PATH/Editor*/}"
          echo "ROOT_PATH=$root_path"
          template_path=$(find "$root_path" -type f -name "com.unity.template.3d*.tgz" | head -n 1)
          # verify that the file exists
          if [ ! -f "$template_path" ]; then
            echo "Template file not found at $template_path"
            exit 1
          fi
          echo "TEMPLATE_PATH=$template_path"
          echo "TEMPLATE_PATH=$template_path" >> "$GITHUB_OUTPUT"

          UNITY_PROJECT_PATH="${{ env.UNITY_PROJECT_PATH }}//\\//}"

          if [ -z "$UNITY_PROJECT_PATH" ]; then
            echo "UNITY_PROJECT_PATH=${{ github.workspace }}/Test Project" >> "$GITHUB_ENV"
          else
            echo "UNITY_PROJECT_PATH=$UNITY_PROJECT_PATH" >> "$GITHUB_ENV"
          fi
        shell: bash
        # Activates the installation with the provided credentials
      - uses: buildalon/activate-unity-license@v1
        with:
          license: 'Personal'
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}
      - uses: ./ # buildalon/unity-action
        name: Create Test Project
        with:
          log-name: 'create-test-project'
          args: '-quit -nographics -batchmode -createProject "${{ env.UNITY_PROJECT_PATH }}" -cloneFromTemplate "${{ steps.template.outputs.TEMPLATE_PATH }}"'
      - run: 'openupm add com.utilities.buildpipeline'
        name: Add Build Pipeline Package
        working-directory: ${{ env.UNITY_PROJECT_PATH }}
      - uses:  ./ # buildalon/unity-action
        name: '${{ matrix.build-target }}-Build'
        with:
          project-path: ${{ env.UNITY_PROJECT_PATH }}
          log-name: '${{ matrix.build-target }}-Build'
          build-target: '${{ matrix.build-target }}'
          args: '-quit -nographics -batchmode -executeMethod Utilities.Editor.BuildPipeline.UnityPlayerBuildTools.StartCommandLineBuild -sceneList Assets/Scenes/SampleScene.unity'
      - uses: actions/upload-artifact@v4
        name: Upload Artifacts
        if: always()
        with:
          name: '${{ github.run_number }}.${{ github.run_attempt }}-${{ runner.os }}-${{ matrix.build-target }}-${{ matrix.unity-version }}-Artifacts'
          path: |
            ${{ github.workspace }}/**/*.log
            ${{ github.workspace }}/**/Builds/${{ matrix.build-target }}/
